name: "CLA Assistant"

on:
  issue_comment:
    types:
      - created
  pull_request_target:
    types:
      - opened
      - closed
      - synchronize

jobs:
  call-workflow-1-in-local-repo:
    uses: tmtecnologia/test-app/.github/workflows/cla.yml@main
    secrets: inherit
